version: '3.7'

services:  
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dssdb
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql-db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      #- ./sql-db/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
volumes:
  database:
    driver: local
