apiVersion: v1
kind: Service
metadata:
  name: dsstestdeploymentservice
spec:
  type: LoadBalancer
  #type: ClusterIP
  selector:
    #app.kubernetes.io/name: dsstest_deploymentpod
    app: dsstest_deploymentpod
  ports:   
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  #type: LoadBalancer